// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniApp.Data;

#nullable disable

namespace MiniApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504032036_AddEpicrisisWithExamenesAuxiliares")]
    partial class AddEpicrisisWithExamenesAuxiliares
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniApp.Models.Epicrisis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Antecedentes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cie10Alta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cie10Ingreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProcedimiento1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProcedimiento2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProcedimiento3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CondicionCurado")
                        .HasColumnType("bit");

                    b.Property<bool>("CondicionEmpeorado")
                        .HasColumnType("bit");

                    b.Property<bool>("CondicionEstacionario")
                        .HasColumnType("bit");

                    b.Property<bool>("CondicionFallecido")
                        .HasColumnType("bit");

                    b.Property<bool>("CondicionMejorado")
                        .HasColumnType("bit");

                    b.Property<string>("DiagnosticoAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticoIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticoNutricional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosisMgKg1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosisMgKg2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosisMgKg3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("EnfermedadActualResumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadiaTotalDias")
                        .HasColumnType("int");

                    b.Property<string>("Evolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvolucionTratamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamenFisico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngresoINSN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngresoOtrosServicios")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngresoServicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrecuenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<int?>("FrecuenciaRespiratoria")
                        .HasColumnType("int");

                    b.Property<string>("HistoriaClinicaNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicacionesAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InmunizacionCompleta")
                        .HasColumnType("bit");

                    b.Property<bool>("InmunizacionIncompleta")
                        .HasColumnType("bit");

                    b.Property<string>("InterconsultaConclusion1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterconsultaConclusion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterconsultaConclusion3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterconsultaEspecialidad1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterconsultaEspecialidad2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterconsultaEspecialidad3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InterconsultaFecha1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InterconsultaFecha2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InterconsultaFecha3")
                        .HasColumnType("datetime2");

                    b.Property<string>("Medicamento1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamento2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamento3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NecropsiaNo")
                        .HasColumnType("bit");

                    b.Property<bool>("NecropsiaSi")
                        .HasColumnType("bit");

                    b.Property<string>("NombreFirmaInterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreFirmaMedicoResidente1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreFirmaMedicoResidente2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreFirmaMedicoTratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nutricional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pendiente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresionArterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procedencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedimientoTerapeutico1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedimientoTerapeutico2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedimientoTerapeutico3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pronostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pulso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Servicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TemperaturaIngreso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TiempoAdministracion1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiempoAdministracion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiempoAdministracion3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TipoAltaFallecido")
                        .HasColumnType("bit");

                    b.Property<bool>("TipoAltaMedica")
                        .HasColumnType("bit");

                    b.Property<bool>("TipoAltaTransferencia")
                        .HasColumnType("bit");

                    b.Property<bool>("TipoAltaVoluntaria")
                        .HasColumnType("bit");

                    b.Property<string>("Via1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Via2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Via3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Epicrisis");
                });

            modelBuilder.Entity("MiniApp.Models.ExamenAuxiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpicrisisId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreExamen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpicrisisId");

                    b.ToTable("ExamenesAuxiliares");
                });

            modelBuilder.Entity("MiniApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MiniApp.Models.ExamenAuxiliar", b =>
                {
                    b.HasOne("MiniApp.Models.Epicrisis", "Epicrisis")
                        .WithMany("ExamenesAuxiliares")
                        .HasForeignKey("EpicrisisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epicrisis");
                });

            modelBuilder.Entity("MiniApp.Models.Epicrisis", b =>
                {
                    b.Navigation("ExamenesAuxiliares");
                });
#pragma warning restore 612, 618
        }
    }
}
